[package]
name = "v4l2-thermal-proxy-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
v4l = "0.14"
libc = "0.2"
image = { version = "0.25", default-features = false }
clap = { version = "4", features = ["derive"] }
ctrlc = "3"
font8x8 = "0.3"
anyhow = "1"

[profile.release]
lto = true
strip = true
